[package]
name = "gutenberg"
version = "0.2.2"
authors = ["Vincent Prouillet <vincent@wearewizards.io>"]
license = "MIT"
readme = "README.md"
description = "Static site generator"
homepage = "https://github.com/Keats/gutenberg"
repository = "https://github.com/Keats/gutenberg"
keywords = ["static", "site", "generator", "blog"]
# build = "build.rs"

[build-dependencies]
clap = "2"

[[bin]]
name = "gutenberg"

[dependencies]
clap = "2"
chrono = "0.4"
toml = "0.4"
term-painter = "0.2"
# Used in init to ensure the url given as base_url is a valid one
url = "1.5"
# Below is for the serve cmd
staticfile = "0.4"
iron = "0.5"
mount = "0.3"
notify = "4"
ws = "0.7"

site = { path = "components/site" }
errors = { path = "components/errors" }
content = { path = "components/content" }
front_matter = { path = "components/front_matter" }
utils = { path = "components/utils" }

[workspace]
members = [
    "components/config",
    "components/content",
    "components/errors",
    "components/front_matter",
    "components/highlighting",
    "components/pagination",
    "components/rendering",
    "components/site",
    "components/taxonomies",
    "components/templates",
    "components/utils",
]

[patch.crates-io]
pest_derive = { git = "https://github.com/jturner314/pest.git", branch = "master" }
tera = { git = "https://github.com/jturner314/tera.git", branch = "master" }
